Fix a lookup error: os.path vs path (arg)
The local argument `path` of `extract(path)` is in conflict with `path`
imported from `os`.

The bug was:

    Traceback (most recent call last):
      File "./test_cgal.py", line 445, in <module>
        main()
      File "./test_cgal.py", line 342, in main
        path_to_extracted_release=extract(path_to_release)
      File "./test_cgal.py", line 104, in extract
        commonprefix = path.commonprefix(tar.getnames())
    AttributeError: 'str' object has no attribute 'commonprefix'